### ISSUE TITLE
Update copies

### ISSUE THREAD

**Issue by gabaldon** [witnet/witnet_wallet#21]
Review current copies and update placeholders.

The copies that need to be updated can be found here: https://github.com/witnet/witnet_wallet/pull/45

**Comment by Tommytrg** [comment]
We have to add copies for three different views:

####  Create or import
Here we could highlight the general properties of the wallet such as: non-custodial, light-wallet or fast, private. Each carrousel's page could have a tittle and the text below.

> Non-custodial. Your private keys are stored encrypted in your device. You have complete control over them.
> Fast. No need to wait to synchronize a whole Witnet node to start using your Wits.
> Private. No data is collected while you are using the app.

#### Login
Here we can add different messages that users don't need to read. Here is where we can include @parodyBit 's proposal about random texts. My only concern about having these texts here is we could deviate the user's attention from the main flow, which is login into the wallet. These texts could fit better while waiting for the sync to finish after creating or importing a wallet. Here are some examples of random texts:

- This wallet is open source so everybody can contribute to it.
- You can use the Sheikah Desktop App as an alternative to this wallet.
- You can learn more about witnet in witnet.io.
- Witnet is live on a lot of networks. Check all the price feeds in the Data Feeds Explorer

#### Import
I'd remove the carrousel here and I'd add only a text explaining the two types of import methods.

> If you already have a wallet, you can import it by using the mnemonic phrase you received when you first created it. You can also use an XPRV text generated from the Light Wallet or Sheikah Wallet.


What do you think? @gabaldon @parodyBit @aesedepece

**Comment by aesedepece** [comment]
> What do you think? @gabaldon @parodyBit @aesedepece

I need to try the app myself again to see the copies in place and make up my mind.

**Comment by aesedepece** [comment]
Hey I have compiled all my copy feedback and suggestions into a Figma document so the comments are matched with screenshots:
https://www.figma.com/file/gAq3TbXfZfVSAvD2P90ROv/Untitled?node-id=0%3A1&t=hUPrOmmnTSCRG0nU-1

**Comment by Tommytrg** [comment]
I'm going to create a PR with these suggestions

**Comment by Tommytrg** [comment]
Closed in #88
