### ISSUE TITLE
Look for a better name than `light wallet`

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet_wallet#47]
- [ ] Decide a better name than `Witnet Light Wallet`
- [ ] Rename repository with the new name

**Comment by aesedepece** [comment]
Here are some (very obvious) suggestions:
- MyWitWallet
- MyWitnetWallet (we've owned mywitnetwallet.com for years)
- Witnet Light Wallet
- Witnet.Light
- Joka / Joka Witnet Wallet
- Witty Wallet
- Witnet Mobile Wallet
- Sheikah Mobile Wallet

**Comment by Tommytrg** [comment]
My personal preference is `Witnet Mobile Wallet` but AFAIK @berrybenry is preparing a way to check with the community what name do they prefer

**Comment by Tommytrg** [comment]
@berrybenry, as we decided, is going to start the campaign asap,
