### ISSUE TITLE
Add a default wallet name in create / import wallet flows

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet_wallet#74]
IMO, adding a name to your wallet shouldn't be mandatory. We should create a default name for the wallet, such as `wallet-$index`, so the user can create or import the wallet without typing anything here.

![image](https://user-images.githubusercontent.com/24905681/232043709-beb2ec64-bd11-4a49-86cf-9fb8baa03ab3.png)

**Comment by parodyBit** [comment]
fixed with:
https://github.com/witnet/witnet_wallet/pull/75
